/// <reference types="cypress"/>
export const data = {
    resourceBronchiolite: {
      approvedOn: /^2022-10-(19|20)$/,
      code: 'bronchiolite',
      collectionStartingYear: '-',
      createdOn: /^2023-03-(09|10)$/,
      dataRowKey: '227',
      description: 'Study aimed at evaluating practices surrounding the management of bronchiolitis at the CHU Sainte Justine.',
      naganoID: 'MP-21-2023-4939',
      name: 'LVC-Bronchiolite-HSJ',
      principalInvestigator: 'Drouin, Olivier',
      tables: 17,
      title: 'Low-value care; and variation in practice for children hospitalized with bronchiolitis at the CHU Sainte-Justine',
      type: 'research_project',
      updatedOn: '2024-10-31',
      variables: {
        totalCount: '123',
        hospitalSystems: {
          clinibaseci: 2,
          icca: 1,
          laboratoire_systeme: 9,
          loinc: 3,
          medecho: 51,
          pericalm: 1,
          pharmacie: 23,
          radimage: 2,
          softlab: 5,
          softmic: 1,
          staturgence: 28,
        },
      },
      version: '-',
    },
    resourceCentro: {
      approvedOn: '-',
      code: 'cscmed',
      collectionStartingYear: '2012',
      createdOn: '-',
      dataRowKey: '307',
      description: 'Comprehensive database of the Centro system used in outpatient clinics. The data includes those collected from standardized forms and also medical reports and notes entered directly into Centro.',
      naganoID: '-',
      name: 'CSC-Med',
      principalInvestigator: '-',
      tables: 1455,
      type: 'hospitalsystems',
      updatedOn: '2025-04-23',
      variables: {
        totalCount: '44098',
        totalCountForSource: '44300',
      },
      version: '-',
    },
    resourceGermes: {
      approvedOn: 'Not Used',
      code: 'surveillancegermes',
      collectionStartingYear: 'Not Used',
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      naganoID: 'Not Used',
      name: 'Germes',
      principalInvestigator: 'Not Used',
      tables: null,
      type: 'Not Used',
      updatedOn: 'Not Used',
      variables: {
        totalCount: 'Not Used',
      },
      version: 'Not Used',
    },
    resourceInhalateurs: {
      approvedOn: 'Not Used',
      code: 'inhalateurs',
      collectionStartingYear: 'Not Used',
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      naganoID: 'Not Used',
      name: 'inhalateurs',
      principalInvestigator: 'Not Used',
      tables: null,
      type: 'eqp',
      updatedOn: 'Not Used',
      variables: {
        totalCount: 'Not Used',
      },
      version: 'Not Used',
    },
    resourceResppa: {
      approvedOn: 'Not Used',
      code: 'Not Used',
      collectionStartingYear: 'Not Used',
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      naganoID: 'Not Used',
      name: 'RESPPA',
      principalInvestigator: 'Not Used',
      tables: null,
      type: 'Not Used',
      updatedOn: 'Not Used',
      variables: {
        totalCount: 'Not Used',
      },
      version: 'Not Used',
    },
    resourceWarehouse: {
      approvedOn: '1969-12-31',
      code: 'warehouse',
      collectionStartingYear: '-',
      createdOn: '1969-12-31',
      description: 'Warehouse tables created from data in the source systems. These tables are organized into domains and each variable is documented following a standard nomenclature.',
      naganoID: '-',
      name: 'warehouse',
      principalInvestigator: '-',
      tables: 19,
      type: 'warehouse',
      updatedOn: '2024-10-31',
      variables: {
        totalCount: '595',
        hospitalSystems: {
          chartmaxx: 2,
          clinibaseci: 1,
          eclinibase: 12,
          etraceline: 35,
          laboratoire_systeme: 30,
          loinc: 3,
          medecho: 22,
          pericalm: 16,
          pharmacie: 97,
          quanum: 1,
          quanum_chartmaxx: 17,
          radimage: 74,
          softlab: 23,
          softmic: 19,
          softpath: 26,
          unic: 20,
          viewpoint: 19,
          viewpoint6: 66,
        },
      },
      version: '-',
    },
    tableAccouchement: {
      createdOn: '2024-11-05',
      dataRowKey: '1188',
      description: 'Information regarding childbirth',
      domain: '-',
      entity: 'delivery',
      name: 'accouchement',
      resourceCode: 'resppa',
      resourceName: 'RESPPA',
      rowFilter: null,
      updatedOn: '2024-11-05',
      variableCount: '11',
    },
    tableMaternalUltrasound: {
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      domain: 'Not Used',
      entity: 'Not Used',
      name: 'maternal_ultrasound',
      resourceCode: 'Not Used',
      resourceName: 'Not Used',
      rowFilter: 'Not Used',
      updatedOn: 'Not Used',
      variableCount: 'Not Used',
    },
    tablePathology: {
      createdOn: '2024-11-04',
      dataRowKey: '1108',
      description: 'Pathology exams',
      domain: 'Pathology',
      entity: 'observation',
      name: 'pathology',
      resourceCode: 'warehouse',
      resourceName: 'warehouse',
      rowFilter: null,
      updatedOn: '2024-11-04',
      variableCount: '36',
    },
    tablePatient: {
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      domain: 'Not Used',
      entity: 'Not Used',
      name: 'patient',
      resourceCode: 'surveillancegermes',
      resourceName: 'Germes',
      rowFilter: 'Not Used',
      updatedOn: 'Not Used',
      variableCount: 'Not Used',
    },
    tableWeeklySummary: {
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      domain: 'Not Used',
      entity: 'Not Used',
      name: 'weekly_summary',
      resourceCode: 'surveillancegermes',
      resourceName: 'Germes',
      rowFilter: 'Not Used',
      updatedOn: 'Not Used',
      variableCount: 'Not Used',
    },
    totalParticipants: '2.5M',
    variableAdmittedCOVID: {
      categories: null,
      createdOn: '2024-11-05',
      dataRowKey: '46063',
      label: 'Number of patients positive COVID that was hospitalized',
      name: '#_Admitted_COVID',
      resourceCode: 'surveillancegermes',
      resourceName: 'Germes',
      source: 'softlab, loinc',
      sources: {
        resource: 'surveillancegermes',
        table: 'patient',
        variable: 'testLabel',
      },
      table: 'weekly_summary',
      type: 'integer',
      updatedOn: '2024-11-05',
    },
    variableSector: {
      categories: {
        CA: 'Cardiology',
        RA: 'Radiology',
        MN: 'Nuclear medicine',
        OG: 'Obstetric and gynecology',
      },
      createdOn: '2024-11-04',
      dataRowKey: 'Not Used',
      label: 'Sector code',
      name: 'sector',
      resourceCode: 'warehouse',
      resourceName: 'warehouse',
      source: 'Not Used',
      sources: {
        resource: 'radimage',
        table: 'requete',
        variable: 'SECTEUR',
      },
      table: 'medical_imaging',
      type: 'string',
      updatedOn: '2025-04-24',
    },
    variableTestLabel: {
      categories: {
        NotUsed: 'Not Used',
      },
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      label: 'Not Used',
      name: 'testLabel',
      resourceCode: 'surveillancegermes',
      resourceName: 'Germes',
      source: 'Not Used',
      sources: {
        NotUsed: 'Not Used',
      },
      table: 'patient',
      type: 'Not Used',
      updatedOn: 'Not Used',
    },
    variableUnicproduct: {
      categories: {
        NotUsed: 'Not Used',
      },
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      label: 'Not Used',
      name: 'unicproduct',
      resourceCode: 'warehouse',
      resourceName: 'warehouse',
      source: 'Not Used',
      sources: {
        NotUsed: 'Not Used',
      },
      table: 'transfusion',
      type: 'Not Used',
      updatedOn: 'Not Used',
    },
  };
  