/// <reference types="cypress"/>
export const data = {
    resourceBronchiolite: {
      approvedOn: /^2022-10-(19|20)$/,
      code: 'bronchiolite',
      collectionStartingYear: '-',
      createdOn: /^2023-03-(09|10)$/,
      dataRowKey: '59',
      description: 'Study aimed at evaluating practices surrounding the management of bronchiolitis at the CHU Sainte Justine.',
      naganoID: 'MP-21-2023-4939',
      name: 'LVC-Bronchiolite-HSJ',
      principalInvestigator: 'Drouin, Olivier',
      tables: 13,
      title: 'Low-value care; and variation in practice for children hospitalized with bronchiolitis at the CHU Sainte-Justine',
      type: 'research_project',
      updatedOn: '2024-08-16',
      variables: {
        totalCount: '107',
        hospitalSystems: {
          clinibaseci: 1,
          icca: 1,
          loinc: 2,
          medecho: 14,
          pharmacie: 9,
          softlab: 5,
          staturgence: 22,
        },
      },
      version: '-',
    },
    resourceCentro: {
      approvedOn: '-',
      code: 'cscmed',
      collectionStartingYear: '2012',
      createdOn: '-',
      dataRowKey: '19',
      description: 'Comprehensive database of the Centro system used in outpatient clinics. The data includes those collected from standardized forms and also medical reports and notes entered directly into Centro.',
      naganoID: '-',
      name: 'CSC-Med',
      principalInvestigator: '-',
      tables: 419,
      type: 'hospitalsystems',
      updatedOn: '2024-08-16',
      variables: {
        totalCount: '13654',
        totalCountForSource: '13700',
      },
      version: '1',
    },
    resourceGermes: {
      approvedOn: 'Not Used',
      code: 'surveillancegermes',
      collectionStartingYear: 'Not Used',
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      naganoID: 'Not Used',
      name: 'Germes',
      principalInvestigator: 'Not Used',
      tables: null,
      type: 'Not Used',
      updatedOn: 'Not Used',
      variables: {
        totalCount: 'Not Used',
      },
      version: 'Not Used',
    },
    resourceInhalateurs: {
      approvedOn: 'Not Used',
      code: 'inhalateurs',
      collectionStartingYear: 'Not Used',
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      naganoID: 'Not Used',
      name: 'inhalateurs',
      principalInvestigator: 'Not Used',
      tables: null,
      type: 'eqp',
      updatedOn: 'Not Used',
      variables: {
        totalCount: 'Not Used',
      },
      version: 'Not Used',
    },
    resourceResppa: {
      approvedOn: 'Not Used',
      code: 'Not Used',
      collectionStartingYear: 'Not Used',
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      naganoID: 'Not Used',
      name: 'RESPPA',
      principalInvestigator: 'Not Used',
      tables: null,
      type: 'Not Used',
      updatedOn: 'Not Used',
      variables: {
        totalCount: 'Not Used',
      },
      version: 'Not Used',
    },
    resourceWarehouse: {
      approvedOn: '-',
      code: 'warehouse',
      collectionStartingYear: '-',
      createdOn: '-',
      description: 'Warehouse tables created from data in the source systems. These tables are organized into domains and each variable is documented following a standard nomenclature.',
      naganoID: '-',
      name: 'warehouse',
      principalInvestigator: '-',
      tables: 15,
      type: 'warehouse',
      updatedOn: '2024-08-16',
      variables: {
        totalCount: '464',
        hospitalSystems: {
          chartmaxx: 18,
          clinibaseci: 1,
          eclinibase: 12,
          etraceline: 35,
          loinc: 3,
          medecho: 13,
          pericalm: 11,
          pharmacie: 83,
          quanum: 1,
          radimage: 74,
          softlab: 21,
          softpath: 38,
          unic: 18,
          viewpoint: 18,
          viewpoint6: 65,
        },
      },
      version: '1',
    },
    tableAccouchement: {
      createdOn: '2024-09-17',
      dataRowKey: '1188',
      description: 'Information regarding childbirth',
      domain: '-',
      entity: 'delivery',
      name: 'accouchement',
      resourceCode: 'resppa',
      resourceName: 'RESPPA',
      rowFilter: null,
      updatedOn: '2024-09-17',
      variableCount: '11',
    },
    tableMaternalUltrasound: {
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      domain: 'Not Used',
      entity: 'Not Used',
      name: 'maternal_ultrasound',
      resourceCode: 'Not Used',
      resourceName: 'Not Used',
      rowFilter: 'Not Used',
      updatedOn: 'Not Used',
      variableCount: 'Not Used',
    },
    tablePathology: {
      createdOn: '2024-08-16',
      dataRowKey: '9',
      description: 'Pathology exams',
      domain: 'Pathology',
      entity: 'observation',
      name: 'pathology',
      resourceCode: 'warehouse',
      resourceName: 'warehouse',
      rowFilter: null,
      updatedOn: '2024-08-16',
      variableCount: '54',
    },
    tablePatient: {
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      domain: 'Not Used',
      entity: 'Not Used',
      name: 'patient',
      resourceCode: 'surveillancegermes',
      resourceName: 'Germes',
      rowFilter: 'Not Used',
      updatedOn: 'Not Used',
      variableCount: 'Not Used',
    },
    tableWeeklySummary: {
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      description: 'Not Used',
      domain: 'Not Used',
      entity: 'Not Used',
      name: 'weekly_summary',
      resourceCode: 'surveillancegermes',
      resourceName: 'Germes',
      rowFilter: 'Not Used',
      updatedOn: 'Not Used',
      variableCount: 'Not Used',
    },
    totalParticipants: '2.5M',
    variableAdmittedCOVID: {
      categories: null,
      createdOn: '2024-09-17',
      dataRowKey: '76476',
      label: 'Number of patients positive COVID that was hospitalized',
      name: '#_Admitted_COVID',
      resourceCode: 'surveillancegermes',
      resourceName: 'Germes',
      source: 'softlab, loinc',
      sources: {
        resource: 'surveillancegermes',
        table: 'patient',
        variable: 'testLabel',
      },
      table: 'weekly_summary',
      type: 'integer',
      updatedOn: '2024-09-17',
    },
    variableSector: {
      categories: {
        CA: 'Cardiology',
        RA: 'Radiology',
        MN: 'Nuclear medicine',
        OG: 'Obstetric and gynecology',
      },
      createdOn: '2024-08-16',
      dataRowKey: 'Not Used',
      label: 'Sector code',
      name: 'sector',
      resourceCode: 'warehouse',
      resourceName: 'warehouse',
      source: 'Not Used',
      sources: {
        resource: 'radimage',
        table: 'requete',
        variable: 'SECTEUR',
      },
      table: 'medical_imaging',
      type: 'string',
      updatedOn: '2024-08-16',
    },
    variableTestLabel: {
      categories: {
        NotUsed: 'Not Used',
      },
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      label: 'Not Used',
      name: 'testLabel',
      resourceCode: 'surveillancegermes',
      resourceName: 'Germes',
      source: 'Not Used',
      sources: {
        NotUsed: 'Not Used',
      },
      table: 'patient',
      type: 'Not Used',
      updatedOn: 'Not Used',
    },
    variableUnicproduct: {
      categories: {
        NotUsed: 'Not Used',
      },
      createdOn: 'Not Used',
      dataRowKey: 'Not Used',
      label: 'Not Used',
      name: 'unicproduct',
      resourceCode: 'warehouse',
      resourceName: 'warehouse',
      source: 'Not Used',
      sources: {
        NotUsed: 'Not Used',
      },
      table: 'transfusion',
      type: 'Not Used',
      updatedOn: 'Not Used',
    },
  };
  