/// <reference types="cypress"/>
export const data = {
    resourceBronchiolite: {
      approvedOn: /^2022-10-(19|20)$/,
      code: 'bronchiolite',
      collectionStartingYear: '-',
      createdOn: /^2023-03-(09|10)$/,
      dataRowKey: '227',
      description: 'Study aimed at evaluating practices surrounding the management of bronchiolitis at the CHU Sainte Justine.',
      naganoID: 'MP-21-2023-4939',
      name: 'LVC-Bronchiolite-HSJ',
      principalInvestigator: 'Drouin, Olivier',
      tables: 17,
      title: 'Low-value care; and variation in practice for children hospitalized with bronchiolitis at the CHU Sainte-Justine',
      type: 'research_project',
      updatedOn: '2024-10-31',
      variables: {
        totalCount: '123',
        hospitalSystems: {
          clinibaseci: 2,
          icca: 1,
          laboratoire_systeme: 9,
          loinc: 3,
          medecho: 51,
          pericalm: 1,
          pharmacie: 23,
          radimage: 2,
          softlab: 5,
          softmic: 1,
          staturgence: 28,
        },
      },
      version: '-',
    },
    resourceCentro: {
      approvedOn: '-',
      code: 'centro',
      collectionStartingYear: '2012',
      createdOn: '-',
      dataRowKey: '181',
      description: 'Information system for the CHU Sainte Justine outpatient clinics including all electronic forms developed in the different hospital departments.',
      naganoID: '-',
      name: 'centro',
      principalInvestigator: '-',
      tables: 419,
      type: 'hostitalsystems',
      updatedOn: '2024-10-31',
      variables: {
        totalCount: '13677',
      },
      version: '-',
    },
    resourceWarehouse: {
      approvedOn: '1969-12-31',
      code: 'warehouse',
      collectionStartingYear: '-',
      createdOn: '1969-12-31',
      description: 'Warehouse tables created from data in the source systems. These tables are organized into domains and each variable is documented following a standard nomenclature.',
      naganoID: '-',
      name: 'warehouse',
      principalInvestigator: '-',
      tables: 16,
      type: 'warehouse',
      updatedOn: '2024-10-31',
      variables: {
        totalCount: '479',
        hospitalSystems: {
          chartmaxx: 2,
          clinibaseci: 1,
          eclinibase: 12,
          etraceline: 35,
          laboratoire_systeme: 30,
          loinc: 3,
          medecho: 22,
          pericalm: 16,
          pharmacie: 97,
          quanum: 1,
          quanum_chartmaxx: 17,
          radimage: 74,
          softlab: 23,
          softmic: 19,
          softpath: 26,
          unic: 20,
          viewpoint: 19,
          viewpoint6: 66,
        },
      },
      version: '-',
    },
  };
  