/// <reference types="cypress"/>
export const CommonTexts = {
    aboutUrl: 'https://recherche.chusj.org/fr/Plateformes-communes/Grandes-initiatives-institutionnelles/UnIC/Guichet-UnIC-pour-les-chercheurs/Accueil',
    catalogPageTitle: 'UnIC Catalog',
    createdOnTooltip: (object: string) => `Creation date of the dictionary for this ${object}`,
    eqpDescription: 'The data dictionaries detailing the characteristics of the dataset variables are produced by UnIC for quality improvement projects. These projects include, for instance, medical act quality assessment projects and projects developed by the quality improvement department (DQEPE).',
    eqpTitle: 'EQP Projects',
    homePageSubtitle: 'Explore UnIC data dictionaries by resource type:',
    homePageTitle: 'UnIC Data Catalog',
    homePageTitleFR: 'Catalogue de l\'UnIC',
    hospitalSystemsDescription: 'The UnIC catalog collects and documents data from more than 25 hospital information systems. These systems include medical, administrative, and logistical data. They encompass, for example, admission and appointment systems, laboratories, pharmacy, and emergency services.',
    hospitalSystems: 'Hospital Systems',
    hospitalSystemsFR: 'Systèmes hospitaliers',
    landingTitle: 'Data portal of Univers Informationnel du CHU Sainte-Justine.',
    landingTitleFR: 'Portail de données de l\'Univers Informationnel du CHU Sainte-Justine.',
    loginButton: 'Login',
    loginButtonFR: 'Connexion',
    participants: 'Participants',
    projects: 'Projects',
    projectsDescription: 'The data dictionaries detailing the characteristics of the dataset variables are produced by UnIC for research projects conducted at the CHUSJ.',
    projectsFR: 'Projets',
    projectsTitle: 'Research Projects',
    resetFiltersButton: 'Reset filters',
    tableDomainTooltip: 'The domain refers to the specific thematic field in which the variables are collected or applied.',
    tableEntityTooltip: 'The entity refers to the object to which the variable is associated (e.g. the variable “age” is associated with “patient”). The entity describes the context or level to which the data pertains.',
    updatedOnTooltip: (object: string) => `Date of the most recent update of the dictionary for this ${object}`,
    userAvatar: 'CN',
    userName: 'cypress',
    signup: 'Sign up',
    signupFR: 'Créer un compte',
    statsTitle: 'Available data',
    statsTitleFR: 'Données disponibles',
    switchLanguage: 'FR',
    variables: 'Variables',
    warehouseDescription: 'The UnIC warehouse consists of a curated set of variables from hospital systems. These variables are organized by domain and documented according to a standard nomenclature to facilitate their use in research.',
    warehouseTitle: 'Warehouse',
  };
  