name: Build

on:
  push:
  pull_request:
    branches:
      - main

env:
  HUSKY: 0  # Disable Husky during CI

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ensure we can build the image
        run: docker build -t test:test .