# .github/workflows/quality.yml
name: Quality CI

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.1]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm run test
    - name: Write test result
      id: tests
      run: |
        echo " " >> results.log
        echo "## Project Coverage and Test" >> results.log
        echo "" >> results.log
        echo "`npm run test:github  2>&1 | sed 's/=//g' | tail -n 11`" >> results.log
        echo " " >> results.log
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: Project Coverage and Test
        path: results.log